### ISSUE TITLE
types

### ISSUE THREAD

**Issue by sodiqit-fsd** [Nurvive/MetaLamp-4-step#14]
Типы всегда с большой буквы
![image](https://user-images.githubusercontent.com/75619091/172842724-d67541ef-dbcb-4293-8d9c-0c6c862c00a7.png)

**Comment by sodiqit-fsd** [comment]
Не понимаю зачем это в типе `State`. Опиши все поля вручную, зачем часть описывать вручуную и добавлять динамичные?
![image](https://user-images.githubusercontent.com/75619091/172842983-e37b718b-0e63-4898-b3b4-6294651f85a3.png)

**Comment by sodiqit-fsd** [comment]
Зачем слайдер складывать в массив?
И потом каждый раз лишние манипуляции делать?
![image](https://user-images.githubusercontent.com/75619091/172843489-c2f5f41d-5750-4235-ac34-8cd8f7f43b37.png)

**Comment by sodiqit-fsd** [comment]
лучше протипизируй поле target в NotifyData, я так понимаю это должен быть юнион из определенных строк.
![image](https://user-images.githubusercontent.com/75619091/172844586-6bad866c-cb68-4974-b072-d43a853a1b48.png)

**Comment by sodiqit-fsd** [comment]
спокойно можно через операнд && сделать, не нужно делать грубокие условия
![image](https://user-images.githubusercontent.com/75619091/172845405-2b6ac3d9-d560-4265-8c30-6c4d0df9c94a.png)

**Comment by sodiqit-fsd** [comment]
setter'ы должны быть названы как свойства(предмет, существительное), но названы как методы(глаголы, действие).

![image](https://user-images.githubusercontent.com/75619091/172845723-cc13cde7-2676-4a26-a41a-d7ebdd2f3a13.png)

**Comment by Nurvive** [comment]
> Не понимаю зачем это в типе `State`.
Это индексная сигнатура, без нее ts ругается, что нельзя обращаться к свойству типом 'string', а если определить только стринг, то надо уже все остальные типы из интерфейса

**Comment by Nurvive** [comment]
> Зачем слайдер складывать в массив? 

Так как на странице можно подключить несколько слайдеров, то каждый созданный слайдер я кладу в массив. Затем,  при применении какого-то метода, jquery передает только jquery-объект в котором хранится корневой элемент, с которым я сравниваю имеющиеся экземпляры слайдера, нахожу нужный и к нему уже применяю метод

**Comment by sodiqit-fsd** [comment]
> > Не понимаю зачем это в типе `State`.
> 
> Это индексная сигнатура, без нее ts ругается, что нельзя обращаться к свойству типом 'string', а если определить только стринг, то надо уже все остальные типы из интерфейса

То что это индексная сигнатура я понимаю, ты и не должен обращаться через string, поля должны быть затипизированы, к каким ты можешь обратиться, у тебя есть определнный набор опций, динамичного ничего там нет.
