### ISSUE TITLE
view

### ISSUE THREAD

**Issue by sodiqit-fsd** [Nurvive/MetaLamp-4-step#18]
зачем нужен reInit? он же по сути состоит из того, что в конструкторе и в методе init, лучше из конструктора все это вынести и использовать везде просто метод init
![image](https://user-images.githubusercontent.com/75619091/172851024-508481d4-2dd5-43f7-a493-1524c4298524.png)

**Comment by sodiqit-fsd** [comment]
Это можно универсализировать, по сути в паре мест отличия, логика почти одинаковая, можно затипизировать какой target изменения и в зависимости от него проводить валидацию и брать сообщение ошибки.
![image](https://user-images.githubusercontent.com/75619091/172851462-3def51f2-e807-4a35-be51-8812d38510e9.png)

**Comment by Nurvive** [comment]
> зачем нужен reInit?

Просто ts ругается, если поля класса не инициализируются в конструкторе, поэтому что-то пришлось оставить

**Comment by Nurvive** [comment]
> Это можно универсализировать, по сути в паре мест отличия, логика почти одинаковая, можно затипизировать какой target изменения и в зависимости от него проводить валидацию и брать сообщение ошибки.

Но тогда же будет один метод вместо двух разных, это не сломает логику и прозрачность?

**Comment by sodiqit-fsd** [comment]
> > Это можно универсализировать, по сути в паре мест отличия, логика почти одинаковая, можно затипизировать какой target изменения и в зависимости от него проводить валидацию и брать сообщение ошибки.
> 
> Но тогда же будет один метод вместо двух разных, это не сломает логику и прозрачность?

не сломает, по сути метод же выполняют одну и ту же функцию, просто отличия в том, какое именно число он меняет, максимальное или минимальное)

**Comment by sodiqit-fsd** [comment]
> > зачем нужен reInit?
> 
> Просто ts ругается, если поля класса не инициализируются в конструкторе, поэтому что-то пришлось оставить

смотри, тогда не копипасти метод init, переопредели значения, а затем вызови снова метод init
