### ISSUE TITLE
ui

### ISSUE THREAD

**Issue by sodiqit-fsd** [Nurvive/MetaLamp-4-step#20]
1) при попытке взять левый бабл, берет правый

https://user-images.githubusercontent.com/75619091/173565008-974cf1f4-bc2a-488c-9a0d-5268de3319c8.mp4

2) поставить всем перемещаемым элементам соответствующий курсор.
3) немного сдвинуть слайдеры, чтобы баблы не перекрывали часть опций.
4) я думаю было бы логично по клику на лейбл перекидывать в значение равное лейблу)
![image](https://user-images.githubusercontent.com/75619091/173565544-35aff7d8-2f87-4b1a-a559-2ca56d4a9c8c.png)
5) поменял min и max
![image](https://user-images.githubusercontent.com/75619091/173565747-f2cf3c01-2567-416e-96b9-f4927eadc058.png)
6) шаг 99, добавить валидация для from, чтобы учитывал шаг
![image](https://user-images.githubusercontent.com/75619091/173566173-6dc858dd-c0d8-485d-8321-6e686ea5fc26.png)
7) опять сломался)
![image](https://user-images.githubusercontent.com/75619091/173566308-25903166-d788-4986-a06a-8505ee852280.png)
8) так левый бабл скрывается под правым и нельзя за него дернуть, поможет только клик по шкале
![image](https://user-images.githubusercontent.com/75619091/173566653-c758e47a-6f46-4627-97a5-603aab9836c8.png)

**Comment by Nurvive** [comment]
> 4. я думаю было бы логично по клику на лейбл перекидывать в значение равное лейблу)
В общем было два варианта, либо расширить зону лейбла, но тогда нельзя кликнуть на значения  близкие к лейблу, либо сделать зоны одинаковыми, чтобы можно было прокликать любое значение. Сделать первый вариант тогда?

**Comment by Nurvive** [comment]
> 5. поменял min и max
> 7. опять сломался)

Можете, пожалуйста, на запись их сломать, а то я у меня не получается?

**Comment by sodiqit-fsd** [comment]
у меня почему то в целом сейчас не работает слайдерм
![image](https://user-images.githubusercontent.com/75619091/174434722-bbf83009-7953-4131-a1d4-68184bccf381.png)

**Comment by sodiqit-fsd** [comment]
> > 4. я думаю было бы логично по клику на лейбл перекидывать в значение равное лейблу)
> 
> В общем было два варианта, либо расширить зону лейбла, но тогда нельзя кликнуть на значения близкие к лейблу, либо сделать зоны одинаковыми, чтобы можно было прокликать любое значение. Сделать первый вариант тогда?

не очень понял, я бы сделал элементы шкалы (числовые значения) кликабельными и задал бы им определенное значение для калькуляции.

**Comment by sodiqit-fsd** [comment]
> > 5. поменял min и max
> > 6. опять сломался)
> 
> Можете, пожалуйста, на запись их сломать, а то я у меня не получается?

https://user-images.githubusercontent.com/75619091/174434894-1b3d7db4-cf8f-417c-a286-d30b046bd44c.mp4

примерно так, но там по-разному ломается

**Comment by Nurvive** [comment]
> не очень понял, я бы сделал элементы шкалы (числовые значения) кликабельными и задал бы им определенное значение для калькуляции.

Так они вместе со всей шкалой кликабельные. Или вы имеете ввиду сделать кликабельными только их, без остальной шкалы?

**Comment by sodiqit-fsd** [comment]
> > не очень понял, я бы сделал элементы шкалы (числовые значения) кликабельными и задал бы им определенное значение для калькуляции.
> 
> Так они вместе со всей шкалой кликабельные. Или вы имеете ввиду сделать кликабельными только их, без остальной шкалы?

у тебя была проблема, если тыкнуть на элемент шкалы, то значение может быть больше или меньше, скорее всего ты смотришь на коорднаты клика, но я бы сделал кликабельными элементы с заданным значением, чтобы по клику на элемент - значение слайдера было равно тому, что было кликнуто.

**Comment by sodiqit-fsd** [comment]
а ты с самого слайдера убрал клик? с зеленой полоски? он также ддолжен быть, ишью была направлена на шкалу
