### ISSUE TITLE
Синтаксис

### ISSUE THREAD

**Issue by Azmodan95** [Nurvive/MetaLamp-4-step#24]
https://github.com/Nurvive/MetaLamp-4-step/blob/32df57409031cb41dcfc5533568ca365e6330164/src/slider/jquery.slider.js#L16

В подобных случаях если у функции отсутствует имя, лучше использовать стрелочную функции или если это метод как в данном случае то можно использовать более современный синтаксис для этого onChangeTo() {}.

**Comment by Azmodan95** [comment]
https://github.com/Nurvive/MetaLamp-4-step/blob/eed6d20b9825a3bc5856af7fe70e1ad552ae7eeb/src/slider/jquery.slider.js#L6
А тут почему не изменил?

---
https://github.com/Nurvive/MetaLamp-4-step/blob/eed6d20b9825a3bc5856af7fe70e1ad552ae7eeb/src/slider/jquery.slider.js#L3
https://github.com/Nurvive/MetaLamp-4-step/blob/eed6d20b9825a3bc5856af7fe70e1ad552ae7eeb/src/slider/jquery.slider.js#L20
https://github.com/Nurvive/MetaLamp-4-step/blob/eed6d20b9825a3bc5856af7fe70e1ad552ae7eeb/src/slider/jquery.slider.js#L171
И тут на стрелочную, нужно было заменить

**Comment by Nurvive** [comment]
Там если заменить на стрелочную ```$.fn.Slider = function (method) {``` вот здесь, то теряется контекст, я вот не знаю как это пофиксить

**Comment by osyka-yuri** [comment]
> Там если заменить на стрелочную `$.fn.Slider = function (method) {` вот здесь, то теряется контекст, я вот не знаю как это пофиксить

Тут все нормально, я ошибся, стрелочные функции не поддерживают привязку контекста
